# Generated by Django 4.0.4 on 2022-05-20 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comment_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='body',
        ),
    ]
